---
- name: Remove druid proxy api
  shell: "docker service rm druid-proxy-api"
  ignore_errors: yes

- name: Deploy druid proxy api service
  shell: "docker service create --replicas {{ druid_proxy_api_replicas }} -p 9001:9001  --name druid-proxy-api --hostname druid-proxy-api --reserve-memory {{ druid_proxy_api_reservation_memory }} --limit-memory {{ druid_proxy_api_limit_memory }}  --network application_default --env-file /home/deployer/env/sunbird_telemetry-service.env  --with-registry-auth {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
